# Generated by Django 4.2.30 on 2026-04-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submenu',
            name='url',
        ),
        migrations.AddField(
            model_name='submenu',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='submenu_files/'),
        ),
    ]
