# Generated by Django 4.2.30 on 2026-09-28 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_websitesection_delete_pagesection'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubMenuContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('paragraph', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='submenu_content/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submenu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='web.submenu')),
            ],
        ),
    ]
