# Generated by Django 4.2.30 on 2026-09-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_submenucontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='submenucontent',
            name='button_text',
            field=models.CharField(blank=True, help_text='Example: Download Brochure, Learn More', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='submenucontent',
            name='button_url',
            field=models.URLField(blank=True, help_text='Optional external link.', null=True),
        ),
        migrations.AddField(
            model_name='submenucontent',
            name='document',
            field=models.FileField(blank=True, help_text='Upload PDF, DOC, DOCX or other useful document.', null=True, upload_to='submenu_documents/'),
        ),
        migrations.AddField(
            model_name='submenucontent',
            name='document_title',
            field=models.CharField(blank=True, help_text='Example: Department Brochure, Treatment Guide', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='submenucontent',
            name='short_description',
            field=models.CharField(blank=True, help_text='Short description shown as supporting information.', max_length=300, null=True),
        ),
    ]
