# Generated by Django 4.2.30 on 2026-09-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_submenucontent_button_text_submenucontent_button_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submenucontent',
            name='document_title',
        ),
        migrations.RemoveField(
            model_name='submenucontent',
            name='short_description',
        ),
        migrations.AddField(
            model_name='submenucontent',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='submenucontent',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submenucontent',
            name='secondary_button_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='submenucontent',
            name='secondary_button_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submenucontent',
            name='button_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='submenucontent',
            name='button_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submenucontent',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='submenu_documents/'),
        ),
    ]
