# Generated by Django 4.2.30 on 2026-09-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_remove_submenucontent_document_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='button_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='button_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
