# Generated by Django 4.2.30 on 2026-09-28 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_banner_button_email_banner_button_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submenucontent',
            name='button_text',
        ),
        migrations.RemoveField(
            model_name='submenucontent',
            name='button_url',
        ),
        migrations.RemoveField(
            model_name='submenucontent',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='submenucontent',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='submenucontent',
            name='order',
        ),
        migrations.RemoveField(
            model_name='submenucontent',
            name='secondary_button_text',
        ),
        migrations.RemoveField(
            model_name='submenucontent',
            name='secondary_button_url',
        ),
        migrations.RemoveField(
            model_name='submenucontent',
            name='updated_at',
        ),
    ]
