# Generated by Django 4.2.30 on 2026-09-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_remove_submenucontent_button_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submenucontent',
            name='document_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
