# Generated by Django 4.2.30 on 2026-09-29 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_submenucontent_document_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='button_email',
        ),
        migrations.AddField(
            model_name='banner',
            name='button_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
