# Generated by Django 4.2.30 on 2026-09-29 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_remove_banner_button_email_banner_button_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='button_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
