# Generated by Django 4.2.30 on 2026-09-29 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_banner_button_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='button_file',
            field=models.FileField(blank=True, null=True, upload_to='banner-files/'),
        ),
        migrations.AddField(
            model_name='banner',
            name='email_button_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
