# Generated by Django 4.2.30 on 2026-09-29 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_banner_button_file_banner_email_button_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='button_email',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='button_file',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='button_text',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='button_url',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='description',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='email_button_text',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='image',
        ),
    ]
