# Generated by Django 4.2.30 on 2026-09-29 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_alter_banner_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavbarContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('paragraph', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='navbar_content/')),
                ('document_name', models.CharField(blank=True, max_length=200, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='navbar_documents/')),
                ('navbar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='web.navbar')),
            ],
        ),
    ]
