# Generated by Django 4.2.30 on 2026-09-29 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_navbarcontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navbarcontent',
            name='document',
        ),
        migrations.RemoveField(
            model_name='navbarcontent',
            name='document_name',
        ),
        migrations.RemoveField(
            model_name='submenucontent',
            name='document',
        ),
        migrations.RemoveField(
            model_name='submenucontent',
            name='document_name',
        ),
        migrations.CreateModel(
            name='SubMenuDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=200)),
                ('document', models.FileField(upload_to='submenu_documents/')),
                ('submenu_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='web.submenucontent')),
            ],
        ),
        migrations.CreateModel(
            name='NavbarDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=200)),
                ('document', models.FileField(upload_to='navbar_documents/')),
                ('navbar_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='web.navbarcontent')),
            ],
        ),
    ]
