# Generated by Django 4.2.30 on 2026-09-29 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_remove_navbarcontent_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('button_type', models.CharField(choices=[('page', 'Page'), ('url', 'External URL'), ('document', 'Document'), ('email', 'Email')], default='page', max_length=20)),
                ('url', models.URLField(blank=True, null=True)),
                ('page_url', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='banner_documents/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='web.banner')),
            ],
        ),
    ]
