# Generated by Django 4.2.30 on 2026-09-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_bannerbutton'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesection',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
