# Generated by Django 4.2.30 on 2026-09-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_websitesection_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitesection',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
